### PR TITLE
Revert "Docs and tutorial"

### PR DESCRIPTION
**Pull request by fvbock**
Reverts qor/qor#19 thought it was into docs branch - not master

### CODE REVIEW

**Comment by bodhi** [comment]
Would be better to just delete the merge commit and re-open #19?

**Comment by fvbock** [comment]
hm. that was auto generated by github when i hit the "revert" button...
will open a new one in a bit.

**Comment by fvbock** [comment]
hm. that was auto generated by github when i hit the "revert" button...
will open a new one in a bit.

**Comment by jinzhu** [comment]
I will force push to original master ;)

So please revert to an old master, then pull again.

**Comment by fvbock** [comment]
hm. not sure what exactly happened now. but it seems that because the revert merge is on master now i cannot merge the docs branch anymore because it wants to delete all the stuff on master...

what's the best way to resolve that?

**Comment by bodhi** [comment]
This is a good place to see what happened: https://github.com/qor/qor/network

**Comment by bodhi** [comment]
In short, you want to do this:

screen shot 2015-07-14 at 3 38 47 pm

And cherry pick 5a4fe417b81b7b81b659916abbf607eb24e2a9be onto master.

**Comment by fvbock** [comment]
ah ok. seems i look just a bit too early. now i just have to solve 1 conflict and then i can merge...

thx.

**Pull request merged**
