### PR TITLE
Rails-like validations

### PR DESCRIPTION
**Pull request by JosephBuchma**
Hey folks! I came from Rails, and this is attempt to make Activerecord-like validations for Gorm.
Work in progress, so I'll be very grateful for any ideas/suggestions.

### CODE REVIEW

**Comment by jinzhu** [comment]
as we discussed in gitter. we will integrate validations with current solution but don't reimplement it again.

**Comment by bodhi** [comment]
@jinzhu do you have a link to the Gitter conversation? Would be nice for a reference.

**Comment by jinzhu** [comment]
@bodhi gitter doesn't support refer its conversation?

Here is the screenshot:

image

**Comment by bodhi** [comment]
> gitter doesn't support refer its conversation?

Oh, that's a shame. Screenshot is good though!

**Pull request closed without merging**
