### PR TITLE
update datetimepicker: add date and datetime two mode

### PR DESCRIPTION
**Pull request by jasonweng**
Replace old datepicker, add datetime mode.

### CODE REVIEW

**Comment by jasonweng** [comment]
screen shot 2015-12-14 at 7 09 11 pm

**Comment by bodhi** [comment]
Have you looked at these?

https://www.google.com/design/spec/components/pickers.html#pickers-time-pickers

**Comment by jasonweng** [comment]
This plugin( https://github.com/CuriousSolutions/DateTimePicker) is bind date and time picker together without third part library( exclude jQuery ), easy to use, simple, lightweight. 

I also found this one http://simeonc.github.io/sc-date-time/material.html, but this one need Angular or Bootstrap. 

> https://www.google.com/design/spec/components/pickers.html#pickers-time-pickers

I know this, this is just components guidelines, not implement or plugin(https://github.com/google/material-design-lite/issues/782). If you insist to follow material design, i can write one or modify base on other time picket library, keep date picker.

**Comment by bodhi** [comment]
> If you insist to follow material design

I don't have any particular love of Material design, but I think the material date pickers are better than the row-of-values-with-plus-minus-steppers style of the image and the plugin you linked to. The interaction style of the plus-minus widget is poor, a clickable monthly calendar is much better. (I also ~~expect~~ hope that Google would have done a decent amount of user testing, and copying theirs is like getting user testing for free :trollface:)

My ideal would be to have *inline* (= not popup/modal) widgets next to the text input field, so you can click *or* type in a date.

**Comment by jasonweng** [comment]
I'll try to write new time picker plugin with material design, follow Kilian's design 
screen shot 2015-12-15 at 5 04 52 pm

and keep current date picker.

**Comment by lswen** [comment]
改好 提交没有?

**Comment by jinzhu** [comment]
#145

**Pull request closed without merging**
