### PR TITLE
fix string to int conversion issue for arguments

### PR DESCRIPTION
**Pull request by fvbock**
had
pq: invalid input syntax for integer: "%!d(MISSING)ude%!"(MISSING)
don't search with strings on int fields
use "%keyword%" only for string keywords

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @fvbock 

I think this is wrong, a field is not string doesn't means it is int? so we should not convert the keyword to int?

**Comment by fvbock** [comment]
agreed. we also need to test for floats. maybe limit the types of fields we allow search on?

the problem is that we get errors like  
pq: invalid input syntax for integer: "%!d(MISSING)ude%!"(MISSING) 
if we use the %% template for numeric values

**Comment by jinzhu** [comment]
@fvbock I have fixed it like this for now. f188358ac2a8474a33b0e8d94d3a1869c70a063e

**Comment by fvbock** [comment]
will give me 
[2015-07-07 17:12:43]  pq: invalid input syntax for integer: "title" 

updated the PR with more type checking...

**Pull request merged**
