### PR TITLE
259 Handle uint64 primary key

### PR DESCRIPTION
**Pull request by raven-chen**
https://github.com/qor/qor/issues/259

### CODE REVIEW

**Comment by willvictor** [comment]
Fixes my issue https://github.com/qor/qor/issues/259

:) 

Thank you!

**Comment by willvictor** [comment]
@raven-chen just wanted to bump this PR in case it had fallen off your radar :)

**Comment by raven-chen** [comment]
@willvictor  thank you! Was busy on other things and totally forgot this 😮‍💨

**Comment by willvictor** [comment]
No worries! Thanks @raven-chen !

**Pull request merged**
